project_id = "oajbgurnrbrryfifxxji"

[functions.backup-run]
verify_jwt = false

[functions.backup-worker]
verify_jwt = false

[functions.backup-schedule]
verify_jwt = false

[functions.backup-config]
verify_jwt = false

[functions.backup-connection-test]
verify_jwt = false